name: Daily Reminder Bot

on:
  schedule:
    - cron: "0 0 * * *"  # UTC 00:00 = 07:00 WIB
  workflow_dispatch:     # bisa juga trigger manual

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run reminder script
        env:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_telegram_reminder.py
